; consts

EFI_BLACK                              = 0x00
EFI_BLUE                               = 0x01
EFI_GREEN                              = 0x02
EFI_CYAN                               = 0x03
EFI_RED                                = 0x04
EFI_MAGENTA                            = 0x05
EFI_BROWN                              = 0x06
EFI_LIGHTGRAY                          = 0x07
EFI_BRIGHT                             = 0x08
EFI_LIGHTBLUE                          = 0x09
EFI_LIGHTGREEN                         = 0x0A
EFI_LIGHTCYAN                          = 0x0B
EFI_LIGHTRED                           = 0x0C
EFI_LIGHTMAGENTA                       = 0x0D
EFI_YELLOW                             = 0x0E
EFI_WHITE                              = 0x0F

EFI_BACKGROUND_BLACK                   = 0x00
EFI_BACKGROUND_BLUE                    = 0x10
EFI_BACKGROUND_GREEN                   = 0x20
EFI_BACKGROUND_CYAN                    = 0x30
EFI_BACKGROUND_RED                     = 0x40
EFI_BACKGROUND_MAGENTA                 = 0x50
EFI_BACKGROUND_BROWN                   = 0x60
EFI_BACKGROUND_LIGHTGRAY               = 0x70
